namespace PowerPointLabs.TextCollection
{
    internal static class AgendaLabText
    {
        #region Action Framework Tags
        public const string RibbonMenuId = "AgendaLabMenu";
        public const string TextAgendaTag = "TextAgenda";
        public const string VisualAgendaTag = "VisualAgenda";
        public const string BeamAgendaTag = "BeamAgenda";
        public const string RemoveAgendaTag = "RemoveAgenda";
        public const string UpdateAgendaTag = "UpdateAgenda";
        #endregion

        #region GUI Text
        public const string RibbonMenuLabel = "Agenda";
        public const string BulletPointButtonLabel = "Create Text Agenda";
        public const string VisualAgendaButtonLabel = "Create Visual Agenda";
        public const string BeamAgendaButtonLabel = "Create Sidebar Agenda";
        public const string UpdateAgendaButtonLabel = "Synchronize Agenda";
        public const string RemoveAgendaButtonLabel = "Remove Agenda";

        public const string RibbonMenuSupertip =
            "Use Agenda Lab to generate professional-looking agendas automatically.\n\n" +
            "To use this feature, you need to group up your into appropriate sections. " +
            "Each section will be used as one item in the agenda.";
        public const string BulletPointSupertip =
            "Generate an agenda in bullet point style.\n\n" +
            "To perform this action, group your slides into sections, then click this button.";
        public const string VisualAgendaSupertip =
            "Generate an agenda in visual style.\n\n" +
            "To perform this action, group your slides into sections, then click this button.";
        public const string BeamAgendaSupertip =
            "Generate agenda side bar for selected slides.\n\n" +
            "To perform this action, group your slides into sections, then click this button.";
        public const string UpdateAgendaSupertip =
            "Synchronize agenda's layout and format with the first (template) slide.\n\n" +
            "To perform this action, make the changes you want on the first (template) slide, then click this button.";
        public const string RemoveAgendaSupertip =
            "Remove agenda generated by PowerPointLabs.\n\n" +
            "To perform this action, click this button";

        public const string ErrorDialogTitle = "Unable to execute action";
        public const string ErrorNoSection = "Please group the slides into sections before generating agenda.";
        public const string ErrorSingleSection = "Please divide the slides into two or more sections.";
        public const string ErrorEmptySection = "Presentation contains empty section(s). Please fill them up or remove them.";
        public const string ErrorAgendaExist = "Agenda already exists. The previous agenda will be removed and regenerated. Do you want to proceed?";
        public const string ErrorAgendaExistTitle = "Confirm Update";
        public const string ErrorNoAgenda = "There is no generated agenda.";
        public const string ErrorNoReferenceSlide = "No reference slide could be found. Either replace the reference slide or regenerate the agenda.";
        public const string ErrorInvalidReferenceSlide = "The current reference slide is invalid. Either replace the reference slide or regenerate the agenda.";
        public const string ErrorSectionNameTooLong = "One of the section names exceeds the maximum size allowed by Agenda Lab. Please rename the section accordingly.";

        // Dialog Boxes
        public const string GeneratingDialogTitle = "Generating...";
        public const string GeneratingDialogContent = "Agenda is generating, please wait...";
        public const string SynchronizingDialogTitle = "Synchronizing...";
        public const string SynchronizingDialogContent = "Agenda is being synchronized, please wait...";

        public const string ReorganiseSidebarTitle = "Reorganise Sidebar";
        public const string ReorganiseSidebarContent = "The sections have been changed. Do you wish to reorganise the items in the sidebar?";

        public const string BeamGenerateSingleSlideDialogTitle = "Generate on all slides";
        public const string BeamGenerateSingleSlideDialogContent = "Only one slide is selected. Would you like to generate the sidebar on all slides instead?";

        // Agenda Content
        public const string TitleContent = "Agenda";

        public const string BulletVisitedContent = "Visited bullet format";
        public const string BulletHighlightedContent = "Highlighted bullet format";
        public const string BulletUnvisitedContent = "Unvisited bullet format";
        public const string BeamHighlightedText = "Highlighted";

        public const string TemplateSlideInstructions =
                            "This slide is used as a ‘Template' for generating agenda slides. Please do not delete this slide.\r" +
                            "Adjust the design of this slide and click the 'Sync Agenda' (in Agenda Lab) to replicate the design in the other slides.";
        #endregion
    }
}
